### ISSUE TITLE
Converts UUID into number

### ISSUE THREAD

**Issue by JRGranell** [mariusc23/express-query-int#6]
Hi, 

Just came across an issue when I sent a UUID/GUID in the query string. This

```
id=106e04cf-344b-4c1c-98a0-002a67df7099
```

becomes

```
id=106
```

Is a custom parser the recommended way to deal with it?

Thanks,

**Comment by grimurd** [comment]
Same problem with IP addresses

**Comment by mariusc23** [comment]
@JRGranell @grimurd Thanks for reporting this issue! I just published 2.0.0 which uses `Number` to parse the strings. This should resolve the issue for both cases.
