### ISSUE TITLE
Values in Array of Objects are not converted to numbers

### ISSUE THREAD

**Issue by rrwen** [mariusc23/express-query-int#7]
Hi,

I have found that values inside an array of objects are not converted to numbers.

## Issue

Given the query string below:

```
?q[$or][0][a][$gt]=1&q[$or][1][d][$lt]=10
```

The result `req.query` below did not parse strings inside the array (e.g. `{"$gt" : "1"}` is still a string):

```json
{"$or": [
  {"a": {"$gt": "1"}},
  {"d":{"$lt":"10"}}
]}
```

## Example

Install dependencies:

```
npm install --save express supertest express-query-int
```

Create file `app.js`:

```javascript
var express = require('express');
var request = require('supertest');
var queryParser = require('express-query-int');

var app = express();
app.use(queryParser());
app.use('/test', function(req, res) {
  console.log(JSON.stringify(req.query));
  res.end();
});

request(app)
  .get('/test?q[$or][0][a][$gt]=1&q[$or][1][d][$lt]=10')
  .expect(200)
  .then(response => {
    console.log('GET /test');
  });
```

Run `app.js`:

```
node app.js
```

**Comment by mariusc23** [comment]
@rrwen I know it's a bit late, but this is live in `3.0.0` now 😄

**Comment by rrwen** [comment]
@mariusc23 Not at all! Just ran the example and it works now - thanks for the fix!
